---
i18n:
  locales: [en, fr]
  default_locale: en
  structure: multiple_files
media_folder: public/images  # Location where files will be stored in the repo
public_folder: public/images  # The src attribute for uploaded media
local_backend: true
backend:
  name: git-gateway
button_block: &button
  label: Button
  name: link
  widget: object
  summary: '{{fields.title}}'
  fields:
    - {label: Title, name: title, widget: string}
    - label: Style
      name: style
      widget: select
      options: [primary, secondary]
      default: primary
    - {label: href, name: href, widget: string}
    - {label: target, name: target, widget: string, required: false}
blocks: &blocks
  - label: Container
    name: container
    widget: object
    fields:
      - label: Spacing
        name: spacing
        widget: select
        options: [none, small, medium, large]
        default: medium
      - label: Blocks
        name: blocks
        widget: list
        types:
        - <<: *button
  - label: Markdown
    name: markdown
    widget: object
    fields:
      - {label: Markdown, name: markdown, widget: markdown}
  - <<: *button
  - label: Event Data
    name: data
    widget: object
    i18n: true
    fields:
      - label: Entries
        name: entries
        widget: list
        summary: '{{fields.key}} – {{fields.value}}'
        fields:
          - {label: Key, name: key, widget: string}
          - {label: Value, name: value, widget: string}
  - label: Highlights
    name: highlights
    widget: object
    i18n: true
    fields:
      - label: Entries
        name: entries
        widget: list
        summary: '{{fields.title}} – {{fields.description}}'
        fields:
          - {label: Image, name: image, widget: image}
          - {label: alt, name: alt, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: URL, name: url, widget: string}
  - label: Sponsors
    name: sponsors
    widget: object
    i18n: true
    fields:
      - label: Entries
        name: entries
        widget: list
        summary: '{{fields.title}}'
        fields:
          - {label: Image, name: image, widget: image}
          - {label: alt, name: alt, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: URL, name: url, widget: string, required: false}
  - label: Schedule
    name: schedule
    widget: object
    i18n: true
    fields:
      - label: Slots
        name: slots
        widget: list
        summary: '{{fields.time}} – {{fields.event}}'
        fields:
          - {label: Time, name: time, widget: string}
          - {label: Event, name: event, widget: string}
collections:
  - label: Data
    name: data
    files:
      - label: Global
        name: global
        file: src/content/global.json
        fields:
          - label: Date
            name: date
            widget: datetime
            default: '{{now}}'
            date_format: DD.MM.YYYY
            time_format: false
            format: YYYY-MM-DDTHH:mm:ss.SSSZ
          - label: Venue
            name: venue
            widget: string
          - label: Location
            name: location
            widget: string
          - label: Email
            name: email
            widget: string
          - label: Website
            name: website
            widget: string
  - label: Pages
    i18n:
      structure: single_file
    name: pages
    files:
      - label: Home Page
        name: home
        file: src/content/home.json
        i18n: true
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - label: Metadata
            name: metadata
            widget: object
            i18n: true
            fields:
              - {label: Title, name: title, widget: string, i18n: true}
              - {label: Description, name: description, widget: string, i18n: true}
          - label: Sections
            name: sections
            widget: list
            i18n: true
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Title Hidden, name: hiddenTitle, widget: boolean, default: false}
              - label: Blocks
                name: blocks
                widget: list
                types: *blocks
