---
i18n:
  locales: [en, fr]
  default_locale: en
  structure: multiple_files

media_folder: src/assets/images  # Location where files will be stored in the repo
public_folder: src/assets/images  # The src attribute for uploaded media

local_backend: true
backend:
  name: git-gateway
collections:
  - label: Pages
    i18n:
      structure: single_file
    name: pages
    files:
      - label: Home Page
        name: home
        file: src/content/home.json
        i18n: true
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Intro, name: intro, widget: markdown, i18n: true}
          - label: Block
            name: blocks
            widget: list
            i18n: true
            types:
              - label: Hero
                name: hero
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
              - label: Footer
                name: footer
                widget: object
                summary: '{{fields.title}}'
                fields:
                  - {label: Title, name: title, widget: string}
